import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Table from "./components/Table";
import Logout from "./components/Logout";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Logout />

        <h1 className={styles.title}>
          Welcome to Dhaval and Tilak&apos;s{" "}
          <a href="https://nextjs.org">Next.js Project!</a>
        </h1>

        <div className={styles.description}>
          <Table />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
